<h2>Array types and conversions between types</h2>

NumPy supports a much greater variety of numerical types than Python does. 
NumPy numerical types are instances of numpy.dtype (data-type) objects, each having unique characteristics. 

In [1]:
import numpy as np

In [2]:
z = np.arange(3, dtype = np.uint8)
z

array([0, 1, 2], dtype=uint8)

Array types can also be referred to by character codes, for example:

In [3]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [4]:
np.array([1, 2, 3], dtype='d')

array([1., 2., 3.])

In [5]:
z.dtype

dtype('uint8')

The data type can also be used indirectly to query properties of the type, such as whether it is an integer:

In [6]:
d = np.dtype(np.int64)
d

dtype('int64')

In [7]:
np.issubdtype(d, np.integer)

True

In [9]:
np.issubdtype(d, np.floating)

False