<h2>Array types and conversions between types</h2>

NumPy supports a much greater variety of numerical types than Python does. 
NumPy numerical types are instances of numpy.dtype (data-type) objects, each having unique characteristics. 

In [1]:
import numpy as np

In [2]:
z = np.arange(3, dtype = np.uint8)
z

array([0, 1, 2], dtype=uint8)

Array types can also be referred to by character codes, for example:

In [3]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [4]:
np.array([1, 2, 3], dtype='d')

array([1., 2., 3.])

In [5]:
z.dtype

dtype('uint8')

The data type can also be used indirectly to query properties of the type, such as whether it is an integer:

In [6]:
d = np.dtype(np.int64)
d

dtype('int64')

In [7]:
np.issubdtype(d, np.integer)

True

In [8]:
np.issubdtype(d, np.floating)

False

To convert the type of an array, use the .astype() method. For example:

In [9]:
z.astype(np.float64)

array([0., 1., 2.])

Sometimes the conversion can overflow, for instance when converting a numpy.int64 value 300 to numpy.int8. NumPy follows C casting rules, so that value would overflow and become 44 (300 - 256). If you wish to avoid such overflows, you can specify that the overflow action fail by using same_value for the casting argument (see also Overflow errors):

In [11]:
z.astype(np.float64, casting="same_value")

array([0., 1., 2.])

<h2>Numerical Date Types</h2>

5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex.
Some types, such as numpy.int_ and numpy.intp, have differing bitsizes, dependent on the platforms (e.g. 32-bit vs. 64-bit CPU architectures). This should be taken into account when interfacing with low-level code (such as C or Fortran) where the raw memory is addressed.

<h2>Data Types for Strings and Bytes</h2>

In addition to numerical types, NumPy also supports storing unicode strings, via the numpy.str_ dtype (U character code), null-terminated byte sequences via numpy.bytes_ (S character code), and arbitrary byte sequences, via numpy.void (V character code).

All of the above are fixed-width data types. They are parameterized by a width, in either bytes or unicode points, that a single data element in the array must fit inside. This means that storing an array of byte sequences or strings using this dtype requires knowing or calculating the sizes of the longest text or byte sequence in advance.

As an example, we can create an array storing the words "hello" and "world!":

In [12]:
np.array(["hello","world!"])

array(['hello', 'world!'], dtype='<U6')

Here the data type is detected as a unicode string that is a maximum of 6 code points long, enough to store both entries without truncation. If we specify a shorter or longer data type, the string is either truncated or zero-padded to fit in the specified width:

In [13]:
np.array(["hello","world!"], dtype="U5")

array(['hello', 'world'], dtype='<U5')

In [14]:
np.array(["hello","world!"], dtype="U7")

array(['hello', 'world!'], dtype='<U7')

We can see the zero-padding a little more clearly if we use the bytes data type and ask NumPy to print out the bytes in the array buffer:

In [15]:
np.array(["hello","world!"], dtype="S7").tobytes()

b'hello\x00\x00world!\x00'

Each entry is padded with two extra null bytes. Note however that NumPy cannot tell the difference between intentionally stored trailing nulls and padding nulls:

In [17]:
x = [b"hello\0\0", b"world"]
a=np.array(x, dtype="S7")
print(a[0])
a[0]==x[0]

b'hello'


False

If you need to store and round-trip any trailing null bytes, you will need to use an unstructured void data type:

In [18]:
a = np.array(x, dtype="V7")
a

array([b'\x68\x65\x6C\x6C\x6F\x00\x00', b'\x77\x6F\x72\x6C\x64\x00\x00'],
      dtype='|V7')

In [19]:
a[0]==np.void(x[0])

array(True)