In [1]:
import numpy as np
from io import StringIO

<h2>Importing data with genfromtxt</h2>

In [2]:
data = "1, 2, 3\n4, 5, 6"

In [3]:
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

Alternatively, we may be dealing with a fixed-width file, where columns are defined as a given number of characters. In that case, we need to set delimiter to a single integer (if all the columns have the same size) or to a sequence of integers (if columns can have different sizes):

<h2>Splitting the lines into columns</h2>

<h4>The delimiter argument</h4>

In [4]:
data = "  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [5]:
data = "123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

<h4>The autostrip argument</h4>

By default, when a line is decomposed into a series of strings, the individual entries are not stripped of leading nor trailing white spaces. This behavior can be overwritten by setting the optional argument autostrip to a value of True:

In [6]:
data = "1, abc , 2\n 3, xxx, 4"


In [7]:
# Without autostrip
np.genfromtxt(StringIO(data),delimiter=",", dtype="|U5")

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [8]:
# With autostrip
np.genfromtxt(StringIO(data),delimiter=",", dtype="|U5", autostrip=True)

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

<h4>The comments argument</h4>

In [9]:
data = """#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""

In [10]:
np.genfromtxt(StringIO(data), comments = '#', delimiter = ",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

<h2>Skipping lines and choosing columns</h2>

<h4>The skip_header and skip_footer arguments</h4>

The values of this argument must be an integer which corresponds to the number of lines to skip

In [11]:
data = "\n".join(str(i) for i in range(10))

In [12]:
np.genfromtxt(StringIO(data))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.genfromtxt(StringIO(data), skip_header=3, skip_footer = 5)

array([3., 4.])

<h4>The usecols argument</h4>

In some cases, we are not interested in all the columns of the data but only a few of them. 

In [14]:
data = "1 2 3\n4 5 6"
#print(data)

In [15]:
np.genfromtxt(StringIO(data), usecols=(0, -1))

array([[1., 3.],
       [4., 6.]])

f the columns have names, we can also select which columns to import by giving their name to the usecols argument, either as a sequence of strings or a comma-separated string:

In [16]:
data = "1 2 3\n4 5 6"

In [17]:
np.genfromtxt(StringIO(data), names="a, b, c", usecols=("a","c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

<h2>Setting the names</h2>

<h4>The name argument</h4>

A natural approach when dealing with tabular data is to allocate a name to each column. 

In [18]:
data = StringIO("1 2 3\n4 5 6")

In [19]:
np.genfromtxt(data, dtype=[(_, np.int_) for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

Another simpler possibility is to use the names keyword with a sequence of strings or a comma-separated string:

In [20]:
data = StringIO("1 2 3\n4 5 6")

In [21]:
np.genfromtxt(data, names="A, B, C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

We may sometimes need to define the column names from the data itself. In that case, we must use the names keyword with a value of True. 

In [22]:
data = StringIO("So it goes\n#a b c\n1 2 3\n 4 5 6")

In [23]:
np.genfromtxt(data, skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [ ]:
<h4>the defaultfmt argument</h4>

If names=None but a structured dtype is expected, names are defined with the standard NumPy default of "f%i", yielding names like f0, f1 and so forth:

In [24]:
data = StringIO("1 2 3\n4 5 6")
np.genfromtxt(data, dtype=[np.int_, np.float64, np.int_])

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In the same way, if we don’t give enough names to match the length of the dtype, the missing names will be defined with this default template:

In [25]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=(np.int_, np.float64, np.int_), names="a")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('a', '<i8'), ('f0', '<f8'), ('f1', '<i8')])

We can overwrite this default with the defaultfmt argument, that takes any format string:

In [26]:
data = StringIO("1 2 3\n4 5 6")
np.genfromtxt(data,dtype=(np.int_, np.float64, np.int_), defaultfmt = "var_%02i" )

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i8'), ('var_01', '<f8'), ('var_02', '<i8')])

<h4>Validating names</h4>

NumPy arrays with a structured dtype can also be viewed as recarray, where a field can be accessed as if it were an attribute.

In [27]:
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', '<f8'), ('y', '<i8')])
x

array([(1., 2), (3., 4)], dtype=[('x', '<f8'), ('y', '<i8')])

In [28]:
x['x']

array([1., 3.])

View the array as a record array:

In [30]:
x = x.view(np.recarray)

In [31]:
x.x

array([1., 3.])

In [32]:
x.y

array([2, 4])

Create a new, empty record array:

In [35]:
np.recarray((2,), dtype=[('x',int),('y',float),('z', int)])

rec.array([(93965767230718, 0.00000000e+000, 42949673011),
           (  137438953524, 6.79038653e-313,          54)],
          dtype=[('x', '<i8'), ('y', '<f8'), ('z', '<i8')])

<h2>Tweaking the conversion</h2>

<h4>The converters argument</h4>

In [36]:
convertfunc = lambda x: float(x.strip("%"))/100.

In [37]:
data = "1, 2.3%, 45.\n6, 78.9%, 0"

In [38]:
names = ("i", "p", "n")

In [39]:
# General case .....
np.genfromtxt(StringIO(data), delimiter=",", names=names)

array([(1., nan, 45.), (6., nan,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [40]:
# Converted case ...
np.genfromtxt(StringIO(data), delimiter=",", names=names,
             converters={1: convertfunc})

array([(1., 0.023, 45.), (6., 0.789,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

The same results can be obtained by using the name of the second column ("p") as key instead of its index (1):

In [41]:
# Using a name for the converter ...
np.genfromtxt(StringIO(data), delimiter=",", names=names,
             converters={"p": convertfunc})

array([(1., 0.023, 45.), (6., 0.789,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [42]:
data = "1, , 3\n 4, 5, 6"
convert = lambda x float(x.strip() or -999)
np.genfromtxt(StringIO(data), demimiter=",",
              converters={1:convert}

SyntaxError: invalid syntax (1697356689.py, line 2)