In [1]:
import tensorflow as tf
import numpy as np

tf.__version__

I0000 00:00:1785672401.711683    5650 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


'2.21.0'

In [2]:
rank_0_tensor = tf.constant(4)
"rank_0_tensor: ",rank_0_tensor

('rank_0_tensor: ', <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [3]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
"rank_1_tensor", rank_1_tensor

('rank_1_tensor',
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>)

In [4]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
    
"rank_2_tensor:\n", rank_2_tensor

('rank_2_tensor:\n',
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>)

In [5]:
np.array(rank_2_tensor)

NameError: name 'rank_2_tensor' is not defined