In [2]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.21.0'

In [5]:
rank_0_tensor = tf.constant(4)
"rank_0_tensor: ",rank_0_tensor

('rank_0_tensor: ', <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [6]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
"rank_1_tensor", rank_1_tensor

('rank_1_tensor',
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>)

In [8]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
    
"rank_2_tensor:\n", rank_2_tensor

('rank_2_tensor:\n',
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>)