In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0, 100, (10,2))

In [4]:
data

array([[19,  4],
       [ 1, 92],
       [ 4,  6],
       [52, 44],
       [30, 92],
       [41, 67],
       [71, 73],
       [66, 23],
       [51,  5],
       [ 8, 66]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [7]:
scaler_model.fit(data)

,"feature_range feature_range: tuple (min, max), default=(0, 1)Desired range of transformed data.","(0, ...)"
,"copy copy: bool, default=TrueSet to False to perform inplace row normalization and avoid acopy (if the input is already a numpy array).",True
,"clip clip: bool, default=FalseSet to True to clip transformed values of held-out data toprovided `feature_range`.Since this parameter will clip values, `inverse_transform` may notbe able to restore the original data... note:: Setting `clip=True` does not prevent feature drift (a distribution shift between training and test data). The transformed values are clipped to the `feature_range`, which helps avoid unintended behavior in models sensitive to out-of-range inputs (e.g. linear models). Use with care, as clipping can distort the distribution of test data... versionadded:: 0.24",False
Name,Type,Value
"data_max_ data_max_: ndarray of shape (n_features,)Per feature maximum seen in the data.. versionadded:: 0.17 *data_max_*","ndarray[float64](2,)","[71.,92.]"
"data_min_ data_min_: ndarray of shape (n_features,)Per feature minimum seen in the data.. versionadded:: 0.17 *data_min_*","ndarray[float64](2,)","[1.,4.]"
"data_range_ data_range_: ndarray of shape (n_features,)Per feature range ``(data_max_ - data_min_)`` seen in the data.. versionadded:: 0.17 *data_range_*","ndarray[float64](2,)","[70.,88.]"
"min_ min_: ndarray of shape (n_features,)Per feature adjustment for minimum. Equivalent to``min - X.min(axis=0) * self.scale_``","ndarray[float64](2,)","[-0.01,-0.05]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,2
"n_samples_seen_ n_samples_seen_: intThe number of samples processed by the estimator.It will be reset on new calls to fit, but increments across``partial_fit`` calls.",int,10
"scale_ scale_: ndarray of shape (n_features,)Per feature relative scaling of the data. Equivalent to``(max - min) / (X.max(axis=0) - X.min(axis=0))``.. versionadded:: 0.17 *scale_* attribute.","ndarray[float64](2,)","[0.01,0.01]"


In [8]:
scaler_model.transform(data)

array([[0.25714286, 0.        ],
       [0.        , 1.        ],
       [0.04285714, 0.02272727],
       [0.72857143, 0.45454545],
       [0.41428571, 1.        ],
       [0.57142857, 0.71590909],
       [1.        , 0.78409091],
       [0.92857143, 0.21590909],
       [0.71428571, 0.01136364],
       [0.1       , 0.70454545]])

In [9]:
scaler_model.fit_transform(data)

array([[0.25714286, 0.        ],
       [0.        , 1.        ],
       [0.04285714, 0.02272727],
       [0.72857143, 0.45454545],
       [0.41428571, 1.        ],
       [0.57142857, 0.71590909],
       [1.        , 0.78409091],
       [0.92857143, 0.21590909],
       [0.71428571, 0.01136364],
       [0.1       , 0.70454545]])

In [10]:
import pandas as pd

In [13]:
mydata = np.random.randint(1, 101, (50,4))

In [14]:
mydata

array([[ 49,  59,  29,  18],
       [ 72,  94,  38,   7],
       [ 82,  59,  12,  52],
       [ 95,  48,   1,  25],
       [ 86,  25,   1,  35],
       [ 81,  99,  66,  25],
       [100,  51,  73,  19],
       [ 93,  94,  75,  63],
       [ 62,  37,  79,  13],
       [ 55,  90,  65,  62],
       [  9,  55,  78,  86],
       [  1,  25,  57,  63],
       [ 52,  41,  76,  76],
       [  2,  63,  34,  50],
       [ 92,  60,  19,   7],
       [ 23,  84,  91,  16],
       [ 16,  30,  61,  88],
       [ 82,  97,  78,  89],
       [ 32,  96,  44,  12],
       [ 86,  39,  25,  95],
       [ 79,   2,  10,  48],
       [ 91,  35,  54,  90],
       [ 75,  74,  39,  84],
       [ 30,  48,  81,  72],
       [ 73,   1,  48,  56],
       [ 34,  15,  93,  12],
       [  7,  67,  37,  76],
       [ 20,  39,  38,  35],
       [ 98,  62,   4,  35],
       [ 20,  42,  56,  95],
       [ 27,  61,  77,  84],
       [ 52,  54,  86,  77],
       [ 45,  65,  86,  78],
       [  2,  38,  91,  27],
       [ 29,  

In [18]:
data= pd.DataFrame(data=mydata, columns=['f1','f2','f3','label'])

In [19]:
data

,f1,f2,f3,label
0,49,59,29,18
1,72,94,38,7
2,82,59,12,52
3,95,48,1,25
4,86,25,1,35
5,81,99,66,25
6,100,51,73,19
7,93,94,75,63
8,62,37,79,13
9,55,90,65,62


In [21]:
X= data[['f1','f2','f3']]

In [22]:
X

,f1,f2,f3
0,49,59,29
1,72,94,38
2,82,59,12
3,95,48,1
4,86,25,1
5,81,99,66
6,100,51,73
7,93,94,75
8,62,37,79
9,55,90,65


In [23]:
y= data['label']

In [24]:
y

0     18
1      7
2     52
3     25
4     35
5     25
6     19
7     63
8     13
9     62
10    86
11    63
12    76
13    50
14     7
15    16
16    88
17    89
18    12
19    95
20    48
21    90
22    84
23    72
24    56
25    12
26    76
27    35
28    35
29    95
30    84
31    77
32    78
33    27
34    84
35    86
36    49
37    78
38    71
39    12
40    46
41     7
42    87
43    88
44    66
45    39
46    28
47    28
48     8
49    97
Name: label, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=101)

In [30]:
X_train.shape

(35, 3)

In [31]:
X_test.shape

(15, 3)